# Generated by Django 5.2 on 2025-04-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_classifier', '0002_systemconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingjob',
            name='gpu_used',
            field=models.BooleanField(default=False, help_text='Whether GPU was used for training'),
        ),
    ]
