# Generated by Django 5.2 on 2025-04-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_classifier', '0002_trainingjob_gpu_used'),
        ('image_classifier', '0003_trainingjob_gpu_used'),
    ]

    operations = [
    ]
